### ISSUE TITLE
multilined cpp function signatures split between param name and datatype

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#14]
I'm getting ready to start exporting docygen XML to sphinx-immaterial (via `breathe` ext), and I noticed that function signatures that are wrapped to multiple lines are confusingly split between the parameter's datatype and name. Observe a test I made without doxygen/breathe (using standard sphinx cpp domain directives):
![image](https://user-images.githubusercontent.com/14963867/137712547-94570da5-1180-4cb3-ab09-8e814545a806.png)
```rst
.. cpp:function:: const MyType Foo(const MyType bar, uint8_t baz, bool flag, uint16_t foobar, int32_t foobaz, unsigned long barbaz)

   Some function description.
```

I'm suspecting the fix should be placed in _apidoc_formatting.py_ of this theme, but I still need to research more about how it detects the directive's domain.

**Comment by 2bndy5** [comment]
I was able to solve this in CSS, but it is ugly as hell. I'll keep learning docutils (whose docs are ironically terrible), but for now I think I'll just add custom CSS to my projects until a more robust solution can be realized.

```css
.md-typeset dl.api-field>dt.sig-wrap .sig-param + .sig-param::before,
.md-typeset dl.objdesc>dt.sig-wrap .sig-param + .sig-param::before,
.md-typeset dl.api-field>dt.sig-wrap .n.sig-param + .kt::before,
.md-typeset dl.objdesc>dt.sig-wrap .n.sig-param + .kt::before,
.md-typeset dl.api-field>dt.sig-wrap .n.sig-param + .n:not(.sig-param)::before,
.md-typeset dl.objdesc>dt.sig-wrap .n.sig-param + .n:not(.sig-param)::before {
    content: "\a     ";
    white-space: break-spaces;
}
```
This still doesn't handle template parameters and the first arg to long function signatures... The later wouldn't be hard, but template descriptions is bit more complex since the entire signature is parsed from 1 long line - implying that we'd have to parse more than 1 set of brackets and determine if template/function/both parameters needs multiple lines.
