### ISSUE TITLE
Python API for custom admonitions

### ISSUE THREAD

**Issue by jbms** [jbms/sphinx-immaterial#183]
Ideally, we would offer a Python API for defining custom admonitions, likely in the form of a config option to be specified in `conf.py`.

Currently it is possible to override the icons for existing admonitions using via the `icon/admonition` theme option, but to define a new admonition type, the user needs to:
1. Create a custom CSS file and add some boilerplate to it: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions
2. Add an entry to the `icon/admonition` theme option.
3. Define a custom sphinx admonition directive for it

It would be nicer if we provided a single option where the user could specify:
- Directive name/names
- CSS class name (maybe same as directive name?)
- Default title
- Colors
- Icon

Ideally, this would emit the necessary additional CSS to a new combined bundle that contains the static pre-generated CSS bundle with any dynamically-generated CSS appended.  That way there is still a single bundle, and we avoid duplicating the additional CSS on every HTML page, as occurs with the current `icon/admonition` theme option.

**Comment by 2bndy5** [comment]
This reads like the details/summary tags (collapsible admonitions) are excluded.

If the CSS is written with a template that emits no whitespace, I suppose it wouldn't need to use software like the Sass compiler.

As far as HTML templates, we'd have to add our generated CSS into base.html inside a Jinja if statement. I'd prefer it if the current (`icon[admonition]`) upstream solution remained in the templates though. We can just discourage its use after this issue is resolved.

**Comment by jbms** [comment]
Supporting the `details` directives as well would make sense --- I just didn't think about that.

Yes, seems reasonable to leave the existing `icons[admonitions]` code in place.

We don't necessarily need to add the generated CSS inline into the HTML at all --- instead we can just replace the normal CSS bundle with a modified one with the extra generated content appended.

Sass provides useful functionality but I think it would significantly complicate the sphinx build to have to invoke sass as part of it; instead we should just emit plain CSS directly (without extra whitespace, as you noted).  The mkdocs-material theme provides suggested CSS to add for defining custom admonitions:

https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions

Perhaps that is basically exactly what is needed?

**Comment by 2bndy5** [comment]
FYI, the upstream CSS has [deprecated many of the alias CSS classes](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#fn:1) - notice that only the remaining CSS classes are [demonstrated in upstream docs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types). So, this would be especially useful for those that want to re-implement them.

**Comment by 2bndy5** [comment]
> Perhaps that is basically exactly what is needed?

Yes. In fact, that CSS example is what I copied into our docs.

---
I just noticed that there are 2 CSS classes that we haven't documented. These classes allow for [inline admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks) on sufficiently wide viewports.

**Comment by 2bndy5** [comment]
>Define a custom sphinx admonition directive for it

I'm trying to imagine how this would get implemented. I think the easiest way would be to provide a `CustomAdmonition` class that can be used in conf.py

```py
sphinx_immaterial_custom_admonitions = [
    CustomAdmonition(
        name="seealso",
        color=(127, 64, 0),  # could use python's colorsys module to uniform use of various color spaces
        icon="octicons/eye-24",  # could also be user defined in static files
        # optional kwargs
        title="See Also",  # could default to self.name.title()
        override=True,  # should default to False, but this example redefines the seealso admonition
    ),
]
```
resulting in CSS like
```css
:root {
  --si-icon--octicons_eye-24: url('data:image/svg+xml;charset=utf-8,<svg ...>...</svg>')
}

.md-typeset .admonition.seealso {
  border-color: rgb(127, 64, 0);
}

.md-typeset .seealso > .admonition-title {
  background-color: rgba(127, 64, 0, 0.1);
  border-color: rgb(127, 64, 0);
}

.md-typeset .seealso > .admonition-title::before {
  background-color: rgb(127, 64, 0);
  -webkit-mask-image: var(--si-icon--octicons_eye-24);
  mask-image: var(--si-icon--octicons_eye-24);
}
```
And the directive could be used like so:
```rst
.. seealso::
    :collapsible: open

    A collapsible admonition that is expanded by default.

.. seealso::
    :collapsible: close

    A collapsible admonition that is closed by default.

.. seealso:: A custom title

    Some content.
```
