### ISSUE TITLE
line numbers could use better visual distinction

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#26]
At first, this felt like a personal style choice, but I've been adding custom CSS to all my docs that use this theme.

```css
.linenos {
  background-color: var(--md-default-bg-color--light);
  margin-right: 0.5rem;
}
```
which transforms 
![image](https://user-images.githubusercontent.com/14963867/142781900-058a7a3a-4fcf-4538-8254-46ee178b0134.png)
into something a little more "legible" like so
![image](https://user-images.githubusercontent.com/14963867/142781952-209f344a-1ab8-4590-ac0c-ec3523c9ca20.png)

---
I was wondering if this CSS change should be considered for this theme. Additionally, I kinda like how line numbers look in the mkdocs-material upstream
![image](https://user-images.githubusercontent.com/14963867/142782052-364bb1af-c643-4c34-802f-8a969f53aee3.png)

**Comment by jbms** [comment]
I agree that the current version is not good, and that the mkdocs-material styling is better.

I don't use line numbers in the tensorstore documentation so I didn't notice the issue.

Ideally we can avoid modifying the css at all, since mkdocs-material may already have some suitable rules, and just modify the HTML output from sphinx to work with it to produce the desired line number styling.

**Comment by 2bndy5** [comment]
code-blocks in mkdocs-material are a stylized table in which the line numbers are a separate column and the literal code is another column. My first impression is that the `code-block` directive would have to overridden to produce this table structure. I don't think it would be simple matter of adding mkdocs-material classes to the html elements since the SCSS specifically looks for `td` and `tr` within an element using `highlightable` class attribute.

**Comment by 2bndy5** [comment]
I just noticed the furo theme renders code blocks' line numbers like so 
![image](https://user-images.githubusercontent.com/14963867/155759242-8f91782e-19f6-476b-8a63-0e05070c0bf2.png)
using 
```css
.highlight span.linenos {
  box-shadow: -.0625rem 0 var(--color-foreground-border) inset;
  display: inline-block;
  margin-right: .875rem;
}
```
This closely resembles mkdocs-material's code-blocks look, but the furo theme doesn't support changes in font-size (deeming such changes as "unstable").
