### ISSUE TITLE
Line block does not preserve indent

### ISSUE THREAD

**Issue by N-Wouda** [jbms/sphinx-immaterial#272]
Hello, thanks for the great work on making this theme available to Sphinx users! I've recently moved over to using sphinx-immaterial and noticed that the line block markup does not preserve indent. This can be seen in [the documentation](https://jbms.github.io/sphinx-immaterial/rst-cheatsheet/rst-cheatsheet.html#blocks):
![image](https://github.com/jbms/sphinx-immaterial/assets/16272507/abdb705a-2daa-4ae1-b424-d8bf171c7693)
I expect this to render as
<img width="495" alt="image" src="https://github.com/jbms/sphinx-immaterial/assets/16272507/a4a6c06b-f02d-4ee5-91ec-77a1f7657a7b">
like in [the docutils example](https://docutils.sourceforge.io/docs/user/rst/quickref.html#line-blocks).

**Comment by 2bndy5** [comment]
I suspect this has something to do with the fact that we don't inherit CSS from a builtin sphinx theme... Looking at the docutils example, there's the following CSS rule:
```css
div.line-block div.line-block {
  margin-left: 1.5em;
}
```
which provides the indent in HTML.

Digging into whatever else we're missing CSS-wise in the basic theme (a commonly inherited sphinx theme), I also see the [following CSS rules](https://github.com/sphinx-doc/sphinx/blob/571becb6afb5383f28aee2d26e4a255b9fdaae11/sphinx/themes/basic/static/basic.css_t#L715C1-L726C1):
```css
.line-block {
    display: block;
    margin-top: 1em;
    margin-bottom: 1em;
}

.line-block .line-block {
    margin-top: 0;
    margin-bottom: 0;
    margin-left: 1.5em;
}
```

I don't think it would be harmful to other HTML elements if we add this CSS to our sphinx.scss file, but I would prefer a more specific selector (like `div.line-block`).

@N-Wouda Thanks for reporting this! Would you like to submit a PR with 
```css
div.line-block {
    display: block;
}

div.line-block div.line-block {
    margin-left: 1.5em;
}
```
added to our [src/assets/stylesheets/main/_sphinx.scss](https://github.com/jbms/sphinx-immaterial/blob/47dfef73f6e141598a8e3aae55a96e3515530a8a/src/assets/stylesheets/main/_sphinx.scss#L90) file?
