### ISSUE TITLE
classes table doesn't take the full width of the article

### ISSUE THREAD

**Issue by 12rambau** [jbms/sphinx-immaterial#288]
I have some small classes in my project with very short descriptions. When using immaterial along with autoapi, the classes table get reduce making it inconsistent with the Functions one: 

<img width="406" alt="image" src="https://github.com/jbms/sphinx-immaterial/assets/12596392/5098a5df-1363-4201-bcfb-407b78e745a4">
 
Is it wanted ?

**Comment by 2bndy5** [comment]
If you mean the tale width being adaptive to its contents, then yes, that is expected.

**Comment by 12rambau** [comment]
ok I'll find the appropriate css selector to change it in custom.css and post it here before closing the issue.

**Comment by 2bndy5** [comment]
Tried doing this already... Found that removing `box-size: inherit` changes the width of the entire table, but the rows/headers need additional tweaking.

Please also remember, the [Material design rules](https://m2.material.io/components/data-tables) are fundamental to this theme (and its upstream source in mkdocs).

**Comment by 12rambau** [comment]
I added the follwing to my  custom.css and it works as expected: 

```css 

/* make autosummary tables use all the width available */
table.autosummary {
  width: 100% !important;
}

table.autosummary tr:not(:last-child) {
  white-space: nowrap !important;
}

table.autosummary td:last-child {
  width: 99% !important;
}
```

Of course as it's my custom one I've been very lazy on the selector description and used !important instead. 

<img width="960" alt="image" src="https://github.com/jbms/sphinx-immaterial/assets/12596392/99bf9ac8-2df4-41e2-bb99-7fee7e19c790">


If it's not a wanted feature feel free to close my issue, if not I can try to find the exact selector in your scss.
