### ISSUE TITLE
[jupiter-book] Missing Table of Contents

### ISSUE THREAD

**Issue by Mrsenior12** [jbms/sphinx-immaterial#331]
I'm using this theme inside `jupyter-book` to generate documentation. Unfortunately in every file excluding "root" file Table of Contents is missing. 

In documentation I could find anything related to that issue :( 

Section with theme configuration in `_config.yml` looks like that:
```yml
sphinx:
  config:
    html_theme: "sphinx_immaterial"
    html_theme_options: {
    "globaltoc_collapse": True,
    "edit_uri": "blob/develop/docs",
    "features": [
      "navigation.expand",
      "navigation.selection",
      "navigation.top",
      "search.share",
      "toc.follow",
      "toc.sticky",
    ],
    "palette": [
        {
            "media": "(prefers-color-scheme: light)",
            "scheme": "default",
            "toggle": {
                "icon": "material/lightbulb-outline",
                "name": "Switch to dark mode",
            }
        },
        {
            "media": "(prefers-color-scheme: dark)",
            "scheme": "slate",
            "toggle": {
                "icon": "material/lightbulb",
                "name": "Switch to light mode",
            }
        },
    ],
  }
  extra_extensions:
  - sphinx_inline_tabs
  - sphinx_immaterial

```
