### ISSUE TITLE
Broken navigation?

### ISSUE THREAD

**Issue by melissawm** [jbms/sphinx-immaterial#429]
I am not sure if this is supposed to be filed here with you or with https://github.com/executablebooks/sphinx-external-toc or some other project.

I have created a minimal reproducer of my problem here: https://github.com/melissawm/minimal-example and deployed it here: https://melissawm.github.io/minimal-example

Basically, what I'm observing is that when I click on any of the Section pages in the navbar, instead of seeing the Section landing page, I see the first subpage on that section. In my example, when I click on "Section 1", I get directed to "Subpage 1" and not "section1.html". I swear this didn't use to be the case until recently, and I'm struggling to understand what changed.

My _toc.yml looks like this;

```
root: index
subtrees:
- entries:
  - file: landing.md
  - file: section1.md
    subtrees:
    - entries:
      - file: subpage_1.md
      - file: subpage_2.md
  - file: section2.md
    subtrees:
    - entries:
      - file: subpage_3.md
```

And inspecting the links in the navbar, the link titled "Section 1" links out to "subpage_1.html".

My initial thought was to check for new releases; sphinx-external-toc hasn't had a new release in a while, but sphinx-immaterial has. So I'm wondering if this could be due to some recent change in mkdocs-material that is impacting how these projects interact?

Honestly I'm pretty lost and just trying to figure this out. If you have any thoughts that would be helpful ❤ 

Thank you!
