### ISSUE TITLE
Content tabs

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#43]
Are [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) supported in this theme? I searched in the docs here, but didn't find any mention. Thanks!

**Comment by 2bndy5** [comment]
No. Not natively. To use content tabs in sphinx-immaterial, we recommend the sphinx-design extension. There are other extensions that get similar results, we use sphinx-design in our docs.

**Comment by 2bndy5** [comment]
We can't support content tabs from the theme because the mkdocs-material theme uses a markdown extension to support content tabs. Since this markdown extension isn't used at all in the sphinx world (myRST parser doesn't even use it), we are forced to use a different solution (like the sphinx-design extension).

The drawback, as you've already noted, is that the CSS styling doesn't align well with the theme's CSS.

**Comment by jbms** [comment]
We could potentially add some type of sphinx-design integration so that the content tabs are styled consistently.

**Comment by 2bndy5** [comment]
> We could potentially add some type of sphinx-design integration so that the content tabs are styled consistently.

I've been avoiding this idea because it would pin us to using sphinx-design exclusively (there are other/simpler implementations out there). And, there's the matter of overriding CSS from the extension; I'm not sure where extensions' CSS are in the cascade relative to the theme's CSS.

**Comment by mhostetter** [comment]
Is it easier/better to add a Sphinx directive in this theme, such as `.. content-tabs::` (which could have similar syntax to `sphinx-design`), that would produce a tabbed window with the Material for Mkdocs theming?

**Comment by 2bndy5** [comment]
> Is it easier/better to add a Sphinx directive in this theme, such as `.. content-tabs::` (which could have similar syntax to `sphinx-design`), that would produce a tabbed window with the Material for Mkdocs theming?

I'm more in favor of this approach since we had to do something like that to support admonitions without a title. We're also considering something like this for line number styles in literal code blocks

**Comment by 2bndy5** [comment]
Just want to make note that synchronizing the common tabs on a certain page requires JS (which we may already have from upstream).

**Comment by jbms** [comment]
Providing our own implementation of content tabs seems reasonable assuming it is not too complicated.

I think in principle it might be possible to synchronize the tabs on a single page without JavaScript using fancy hidden form elements or something, but I think certainly synchronizing across multiple pages would require JavaScript in any case.

Unfortunately the cross-page synchronization of tabs is an "insider's only" feature in mkdocs-material so we would have to reimplement that if we want it:
https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs

**Comment by 2bndy5** [comment]
I started looking closer at this. It looks like mkdocs-material implements the content tabs completely [in TS](https://github.com/jbms/sphinx-immaterial/blob/6ceccff8d865208ffbdbbe5feef814936d659835/src/assets/javascripts/components/content/tabs/index.ts) where the HTML is just placeholders (with string-concatenated `id` attributes) for the TS, and [the CSS](https://github.com/jbms/sphinx-immaterial/blob/6ceccff8d865208ffbdbbe5feef814936d659835/src/assets/stylesheets/main/extensions/pymdownx/_tabbed.scss) seems strictly aesthetic. All user interaction seems to trigger a response from _src/assets/javascripts/components/content/tabs/index.ts_.

I'm still learning TypeScript, so reverse engineering a docutils based solution to interact with the TS may be more complex than I originally thought.

**Comment by jbms** [comment]
I am quite familiar with JavaScript but I am not familiar with rxjs, and I also find that the mkdocs-material javascript code can, unfortunately, be rather difficult to follow at times.

I would suggest ignoring the javascript and just looking at the HTML output from mkdocs/mkdocs-material for content tabs --- that is all that we need to replicate.

**Comment by 2bndy5** [comment]
@mhostetter In the meantime, you can use the following to get sphinx-design tabs to look like mkdocs-material's content tabs:
```css
/* *********************** sphinx-design tab-set style overrides ********************* */

.sd-tab-set>input:checked+label {
  border-color: var(--md-primary-fg-color);
  color: var(--md-primary-fg-color);
}

.sd-tab-set>input+label {
  font-size: 0.64rem;
}

.sd-tab-set>input:not(:checked)+label:hover {
  color: var(--md-primary-fg-color);
}
```

---
@jbms I only took a peek at the JS because the html seems heavily reliant on using `id` attributes.
```html
<div class="tabbed-set tabbed-alternate" data-tabs="3:2" style="--md-indicator-x: 0px; --md-indicator-width: 113px;">
  <input checked="checked" id="__tabbed_3_1" name="__tabbed_3" type="radio"><input id="__tabbed_3_2" name="__tabbed_3"
    type="radio">
  <div class="tabbed-labels"><label for="__tabbed_3_1">Unordered list</label><label for="__tabbed_3_2">Ordered
      list</label></div>
  <div class="tabbed-content">
    <div class="tabbed-block">
      <ul>
        <li>Sed sagittis eleifend rutrum</li>
        <li>Donec vitae suscipit est</li>
        <li>Nulla tempor lobortis orci</li>
      </ul>
    </div>
    <div class="tabbed-block">
      <ol>
        <li>Sed sagittis eleifend rutrum</li>
        <li>Donec vitae suscipit est</li>
        <li>Nulla tempor lobortis orci</li>
      </ol>
    </div>
  </div>
</div>
```
Notice it keeps track of tabbed set and tab order number. `__tabbed_3_1` is the first tab on the third set of tabs for that page. I think the `data-tabs` attribute sets the bounds for JS manipulation (doesn't seem to change depending on active tab).

**Comment by jbms** [comment]
I think this is the pymdown extension that produces the tab output:
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/

It sounds like mkdocs-material uses the "alternate_style" output described at the bottom of the page.

**Comment by 2bndy5** [comment]
Ah yes. I wasn't a big fan of how sphinx-design tabs wrapped into multiple lines for mobile's portrait viewport. That certainly helps. I'm imagining the new RST directives like so
```rst
.. md-tab-set::

   .. md-tab-item:: Label 1

      Some content.

   .. md-tab-item:: Label 2

      Some other content.
```

**Comment by 2bndy5** [comment]
I have locally created/tested the necessary directives (`md-tab-set` & `md-tab-item`) to make use of the content tabs feature from upstream... stayed tuned. I'm currently looking into whatever else can/should be supported in this manner

**Comment by mhostetter** [comment]
Awesome @2bndy5! I'll test everything with my project when you're ready to share. Thanks for the help! 😄

**Comment by 2bndy5** [comment]
@mhostetter Please update sphinx-immaterial to v0.4.0 to use [the new directives](https://sphinx-immaterial.readthedocs.io/en/stable/content_tabs.html)

**Comment by mhostetter** [comment]
Great! Thank you, @2bndy5!

**Comment by mhostetter** [comment]
I am now using `.. md-tab-set::` and `.. md-tab-item::` in most places in my docs. There are a few places where I still rely on synced tabs, and so I'm still using `sphinx-design` for that.

Thanks to @2bndy5's initial set of CSS tweaks, I refined them to match Material for Mkdocs even more. So for anyone interested, here is the current set of CSS I'm adding to make `.. tab-set::` and `.. tab-item::` from `sphinx-design` match the content tabs from this theme.

(There may be some silly things here. I'm new to CSS and don't really know what I'm doing.)

```css
.sd-tab-set>input+label {
  font: var(--md-text-font-family);
  font-size: 0.64rem;
  font-weight: bolder;
  border-bottom: .13rem solid transparent;
}
.sd-tab-set>input:checked+label {
  border-color: var(--md-accent-fg-color);
  color: var(--md-accent-fg-color);
}
.sd-tab-set>input:not(checked)+label {
  color: var(--md-default-fg-color--light);
}
.sd-tab-set>input:not(:checked)+label:hover {
  border-bottom: .0rem solid transparent;
  color: var(--md-accent-fg-color);
}
.sd-tab-content {
  box-shadow: 0 -0.05rem var(--md-default-fg-color--lightest);
}
```

Top is `.. tab-set::` and bottom is `.. md-tab-set::`.

![image](https://user-images.githubusercontent.com/12112573/159384054-be8ba627-b954-46a2-9fed-685a686c4edf.png)
