### ISSUE TITLE
[question] How to change the icon of an admonition?

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#5]
My intention is to have 
![image](https://user-images.githubusercontent.com/14963867/136675648-5a51c27b-b07f-4921-8a7a-06f9841b7a4c.png)
look like
![image](https://user-images.githubusercontent.com/14963867/136675659-63bce8d4-418c-46d8-83c6-538c1557a4fc.png)

But it looks like the built theme only allows a limited set of options. So, how do I change the icon for admonitions? Usually I'd override the CSS styling to do this, but I don't see the compiled svg I want.

**Comment by 2bndy5** [comment]
## Solution
This info should go in the revised sphinx-immaterial docs since the theme's assets are programmatically optimized before distribution.

1. Find the desired icon from the https://materialdesignicons.com/ listing
2. copy the "Inline SVG for HTML" code
3. paste it into 
   ```css
   .md-typeset .admonition.tip .admonition-title::before {
     mask-image: url('data:image/svg+xml;charset=utf-8,{copied code goes here}'); /* no the curly brackets */
     background-color: hsl(301, 100%, 63%); /* to change the color of the icon (if desired) */
   }
   ```

This method does not work well with nested admonitions, but I may be overriding the CSS poorly.

**Comment by 2bndy5** [comment]
Well. I found the icons listed on https://materialdesignicons.com/, but they have style data embedded in the SVG code.
I was able to get it working by copying the SVG code from the site and then
1. replace the `style="width:24px;height:24px" ` with `xmlns="http://www.w3.org/2000/svg" ` in the beginning `<svg>` tag
2. remove the `fill="currentColor" ` from the `<path>` tag's content
3. put altered svg code into a `mask-image` attribute for the css rule

Results:
```css
.md-typeset .admonition.tip .admonition-title::before,
.md-typeset .admonition.hint .admonition-title::before {
  mask-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12,3L1,9L12,15L21,10.09V17H23V9M5,13.18V17.18L12,21L19,17.18V13.18L12,17L5,13.18Z" /></svg>');
}
```

**Comment by 2bndy5** [comment]
In case anyone has trouble with this solution after updating to sphinx-immaterial v0.3, the CSS rules have changed a bit. The following can be used to change the admonition's color and title icon:
```css
/* changing the style for the `.. seealso::` admonition */

.md-typeset .admonition.seealso>.admonition-title::before {
  mask-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M572.52 241.4C518.29 135.59 410.93 64 288 64S57.68 135.64 3.48 241.41a32.35 32.35 0 0 0 0 29.19C57.71 376.41 165.07 448 288 448s230.32-71.64 284.52-177.41a32.35 32.35 0 0 0 0-29.19zM288 400a144 144 0 1 1 144-144 143.93 143.93 0 0 1-144 144zm0-240a95.31 95.31 0 0 0-25.31 3.79 47.85 47.85 0 0 1-66.9 66.9A95.78 95.78 0 1 0 288 160z"/></svg>');
  background-color: hsl(301, 100%, 63%);
}

.md-typeset :is(.admonition):is(.seealso) {
  border-color: hsl(301, 100%, 63%);
}

.md-typeset :is(.seealso) > :is(.admonition-title) {
  background-color: hsla(287, 100%, 63%, 0.25);
  border-color: hsl(301, 100%, 63%);
}
```
